SET SERVEROUTPUT ON SIZE 1000000;
SET VERIFY OFF;


BEGIN
   FOR c IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE ('DROP TABLE "' || c.table_name || '" CASCADE CONSTRAINTS');
   END LOOP;
   FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
      EXECUTE IMMEDIATE ('DROP SEQUENCE "' || s.sequence_name || '"');
   END LOOP;
END;
/


CREATE SEQUENCE village_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE villager_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE complaint_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE project_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE resource_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE review_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE VILLAGES (
    VILLAGE_ID NUMBER PRIMARY KEY,
    VILLAGE_NAME VARCHAR2(100) NOT NULL,
    VILLAGE_CODE VARCHAR2(20) UNIQUE NOT NULL,
    POPULATION NUMBER,
    TOTAL_FAMILIES NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE VILLAGERS (
    VILLAGER_ID NUMBER PRIMARY KEY,
    VILLAGE_ID NUMBER REFERENCES VILLAGES(VILLAGE_ID),
    VILLAGER_NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER(3),
    OCCUPATION VARCHAR2(100),
    PHONE VARCHAR2(15)
);

CREATE TABLE COMPLAINTS (
    COMPLAINT_ID NUMBER PRIMARY KEY,
    VILLAGER_ID NUMBER REFERENCES VILLAGERS(VILLAGER_ID),
    VILLAGE_ID NUMBER REFERENCES VILLAGES(VILLAGE_ID),
    COMPLAINT_TYPE VARCHAR2(50),
    COMPLAINT_TITLE VARCHAR2(200) NOT NULL,
    COMPLAINT_DESCRIPTION VARCHAR2(2000),
    LOCATION VARCHAR2(200),
    PRIORITY_LEVEL VARCHAR2(20),
    STATUS VARCHAR2(30) DEFAULT 'PENDING',
    FILED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE DEVELOPMENT_PROJECTS (
    PROJECT_ID NUMBER PRIMARY KEY,
    VILLAGE_ID NUMBER REFERENCES VILLAGES(VILLAGE_ID),
    PROJECT_NAME VARCHAR2(200) NOT NULL,
    BUDGET_ALLOCATED NUMBER(12,2),
    BUDGET_SPENT NUMBER(12,2) DEFAULT 0,
    COMPLETION_PERCENTAGE NUMBER(5,2) DEFAULT 0,
    PROJECT_STATUS VARCHAR2(30) DEFAULT 'PLANNED'
);

CREATE TABLE RESOURCES (
    RESOURCE_ID NUMBER PRIMARY KEY,
    VILLAGE_ID NUMBER REFERENCES VILLAGES(VILLAGE_ID),
    RESOURCE_TYPE VARCHAR2(50),
    RESOURCE_NAME VARCHAR2(100),
    TOTAL_COUNT NUMBER,
    COVERAGE_PERCENTAGE NUMBER(5,2),
    QUALITY_STATUS VARCHAR2(20)
);

CREATE TABLE WORK_REVIEWS (
    REVIEW_ID NUMBER PRIMARY KEY,
    PROJECT_ID NUMBER REFERENCES DEVELOPMENT_PROJECTS(PROJECT_ID),
    VILLAGER_ID NUMBER REFERENCES VILLAGERS(VILLAGER_ID),
    QUALITY_RATING NUMBER(1),
    REVIEW_COMMENTS VARCHAR2(1000),
    REVIEW_DATE DATE DEFAULT SYSDATE
);


INSERT INTO VILLAGES VALUES (village_seq.NEXTVAL, 'रामपुर गांव', 'VIL001', 856, 180, 'ACTIVE', SYSDATE);
INSERT INTO VILLAGES VALUES (village_seq.NEXTVAL, 'श्यामपुर गांव', 'VIL002', 1250, 245, 'ACTIVE', SYSDATE);

INSERT INTO VILLAGERS VALUES (villager_seq.NEXTVAL, 1, 'Shyam Lal', 35, 'FARMER', '9876543211');
INSERT INTO VILLAGERS VALUES (villager_seq.NEXTVAL, 2, 'Mohan Singh', 42, 'SHOPKEEPER', '9876543212');

INSERT INTO COMPLAINTS VALUES (complaint_seq.NEXTVAL, 1, 1, 'WATER', 'पानी की समस्या - रामपुर', '3 दिन से पानी नहीं आ रहा', 'रामपुर चौराहा', 'URGENT', 'IN_PROGRESS', SYSDATE - 2/24);
INSERT INTO COMPLAINTS VALUES (complaint_seq.NEXTVAL, 2, 2, 'ROADS', 'सड़क की हालत - श्यामपुर', 'मुख्य सड़क में बड़े गड्ढे', 'मुख्य बाजार', 'HIGH', 'PENDING', SYSDATE - 5/24);

INSERT INTO DEVELOPMENT_PROJECTS VALUES (project_seq.NEXTVAL, 1, 'पानी की टंकी निर्माण', 520000, 390000, 75, 'IN_PROGRESS');
INSERT INTO DEVELOPMENT_PROJECTS VALUES (project_seq.NEXTVAL, 2, 'सड़क मरम्मत', 850000, 382500, 45, 'IN_PROGRESS');

INSERT INTO RESOURCES VALUES (resource_seq.NEXTVAL, 1, 'WATER', 'पानी की टंकी', 15, 85, 'GOOD');
INSERT INTO RESOURCES VALUES (resource_seq.NEXTVAL, 1, 'ELECTRICITY', 'बिजली लाइन', 8, 95, 'GOOD');
INSERT INTO RESOURCES VALUES (resource_seq.NEXTVAL, 1, 'ROAD', 'मुख्य सड़क', 3, 70, 'AVERAGE');
INSERT INTO RESOURCES VALUES (resource_seq.NEXTVAL, 1, 'HEALTH', 'स्वास्थ्य केंद्र', 3, 60, 'POOR');

COMMIT;
PROMPT Database setup complete!
